# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

  filelog:
    include_file_path: true
    include:
      - /var/log/pods/*/*/*.log
      - /var/lib/docker/containers/*/*-json.log
    operators:
      - id: container-parser
        type: container
        format: docker
        add_metadata_from_filepath: false

exporters:
  debug:
    verbosity: detailed

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  otlphttp/prometheus:
    endpoint: "http://prometheus:9090/api/v1/otlp"
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

processors:
  batch:

  resourcedetection:
    detectors: [env, docker]
    timeout: 10s

connectors:
  spanmetrics:
    exemplars:
      enabled: true
      max_per_data_point: 10000

service:
  telemetry:
    logs:
      level: INFO
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [spanmetrics, otlp/tempo]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch, resourcedetection]
      exporters: [otlphttp/prometheus]
    logs:
      receivers: [otlp, filelog]
      processors: [batch, resourcedetection]
      exporters: [otlphttp/loki]
